language: node_js
node_js:
- '8'
script:
- npm test
deploy:
  provider: npm
  email: apexearth@gmail.com
  api_key:
    secure: Gg5AI65aX78QcUTVcH1vgfp7n0TSyu+3nwIAqbIdd/odjr1GbfQwCOPxVtCBoP0m448eoZ4ONiUIuy83nRx30dkuM6QjYYps+oH5eb2RMJ2AL92bpCRoH2N2q/YiVYsBn+YNd8RN97sgd0aGUNS2k+6zd1xXvkiiPGG1xWrP5xjsomtW638A+Wciu/RyASBrsUR+5V9lUXfl7BP0P+wGBtg4tCRaU7AeCtctf7km8LpU/yunsk/HulmGqFEqYMpYgOlnNotlextGpR6NhqnjPQWfn2P02nsAc3EPd7JWhX3naSypPK3uyyH92xW1nGAUgwAuGa+LJRMdnrMaukV3sBgB4yM9veMRyztpNJmiU8739EBA2q9IdpCILWbLzluMnluHfFnrhv59h8uiioaSreyJusLWNRXAeQhvDokfU9zJzki1DgWNhqJGPdi+sobthTpWmIs6os/QxWlY+ddFdspnbmhYTXtVKyjlgzEwBTDU7LFUSIiFgmxSMRwAsTB0SqxYyqQxv4zGlAXd11rDoYb74xN6YNmt/8mEU9WSynSidCnHZGE89/GVvdCcYTqNE+TPW1ZbWFvTRXk0cq+GBhUreO91gdl1WEx1b+zoz7ayAdFKi9UElzyA9KrP8dXCMxw+Gjo/iBunXxPUmFh3YBvMzqJb++HGkWmDEzb7kac=
  on:
    tags: true
    repo: apexearth/layout
